version: "2"

linters:
  default: none
  enable:
    - gologanalizer

  settings:
    custom:
      gologanalizer:
        type: "module"
        description: "My custom log analyzer"
        settings:
          check-lowercase: true
          check-english: true
          check-symbols: true
          check-sensitive: true
          sensitive-patterns:
            - "(?i)password"
            - "(?i)token"
            - "(?i)api[_-]?key"
            - "(?i)secret"
            - "(?i)credentials"
            - "(?i)auth"